version: '3.8'
services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    container_name: typescript-node
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://localhost:27017/marketplace-app
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ../mongo_data:/data/db
